# Generated by Django 4.1.6 on 2023-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_rename_description_task_descriptions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="Descriptions",
            field=models.TextField(blank=True),
        ),
    ]
